max_width = 80
use_small_heuristics = "Max"
use_field_init_shorthand = true
newline_style = "Unix"

# unstable features
unstable_features = true
imports_granularity = "Crate"
wrap_comments = true
comment_width = 80
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true

error_on_line_overflow = true
error_on_unformatted = true
